# Generated by Django 2.2.2 on 2019-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='about',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
